name: Deploy Production CGK
on:
  workflow_dispatch:
  push:
    branches: [ master, add/gh-action-prod ]

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build and deploy
        run: npm run deploy  # Replace with your actual deployment command

  trigger-versioning:
    name: Trigger Versioning and Confluence Update
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check if rerun
        id: check-rerun
        run: |
          if [ "${{ github.event.workflow_run.conclusion }}" == "success" ]; then
            echo "This is a fresh run"
            echo "rerun=false" >> $GITHUB_ENV
          else
            echo "This is a rerun"
            echo "rerun=true" >> $GITHUB_ENV
          fi
          echo "::set-output name=rerun::${{ env.rerun }}"

      - name: Trigger Versioning and Confluence Workflow
        if: steps.check-rerun.outputs.rerun == 'false'
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Content-Type: application/json" \
          --data '{"event_type":"versioning_trigger"}' \
          https://api.github.com/repos/${{ github.repository }}/dispatches
